import type { SearchItem } from "./types";

/** Static catalog: live pages, hubs, planned guides (from about + webiste_info). */
export const staticSearchCatalog: SearchItem[] = [
  // Core pages
  {
    id: "page-home",
    title: "Home",
    href: "/",
    description: "Your local partner for independent China travel — planning, prep, and practical guides.",
    type: "page",
    keywords: ["hidden china travel", "start"],
  },
  {
    id: "page-about",
    title: "About Hidden China Travel",
    href: "/about",
    description: "Meet Joy Liu and why this site exists for foreign travelers.",
    type: "page",
    keywords: ["founder", "joy liu", "kunming"],
  },
  {
    id: "page-privacy",
    title: "Privacy Policy",
    href: "/privacy-policy",
    description: "How we collect, use, and protect your information.",
    type: "page",
    keywords: ["legal", "privacy", "cookies"],
  },
  {
    id: "page-terms",
    title: "Terms of Service",
    href: "/terms-of-service",
    description: "Terms for using the site, paid planning services, and payments.",
    type: "page",
    keywords: ["legal", "terms", "refund", "stripe", "tos"],
  },
  {
    id: "page-survival-guides",
    title: "Survival Guides",
    href: "/survival-guides",
    description: "Step-by-step guides for payments, transport, and daily life in China.",
    type: "page",
    keywords: ["guides", "articles", "blog"],
  },
  {
    id: "page-china-destinations",
    title: "China Destinations",
    href: "/china-destinations",
    description:
      "First-base cities for foreign visitors — Beijing, Shanghai, Xi’an, Chengdu, Yunnan, and more.",
    type: "page",
    keywords: [
      "destinations",
      "cities",
      "beijing",
      "shanghai",
      "yunnan",
      "chongqing",
      "zhangjiajie",
      "guangzhou",
    ],
  },
  {
    id: "page-yunnan",
    title: "Independent Yunnan: a 7-day Kunming–Dali–Lijiang loop",
    href: "/china-destinations/yunnan",
    description:
      "Independent Kunming–Dali–Lijiang week: Erhai, Jade Dragon, Shuhe, and a Kunming landing. Custom PDF $129 early bird (6–10 days), not $99.",
    type: "page",
    keywords: [
      "yunnan",
      "dali",
      "lijiang",
      "kunming",
      "xishuangbanna",
      "independent yunnan travel",
      "yunnan without a tour",
      "7 days in yunnan",
      "kunming dali lijiang itinerary",
      "best time to visit yunnan",
      "spring city kunming",
      "yunnan four seasons",
      "四季如春",
      "yunnan food",
      "prepare yunnan trip",
    ],
  },
  {
    id: "page-survival-kit",
    title: "China Digital Survival Kit",
    href: "/survival-kit",
    description:
      "Pre-trip checklist: eSIM, Alipay, VPN, hotels, trains, tickets — then plan your route.",
    type: "tool",
    keywords: ["survival", "kit", "checklist", "esim", "alipay", "vpn", "prep"],
  },

  // Tools
  {
    id: "tool-index",
    title: "Tools",
    href: "/tools",
    description: "Online planners and utilities for China travel.",
    type: "tool",
    keywords: ["utilities", "apps"],
  },
  {
    id: "tool-visa",
    title: "China Visa Checker",
    href: "/china-visa-checker",
    description:
      "Check visa-free, 240-hour transit, or tourist visa needs by passport — or browse country pages for US, UK, India, Vietnam, Kyrgyzstan, and more.",
    type: "tool",
    keywords: [
      "visa",
      "visa-free",
      "240",
      "transit",
      "entry",
      "vietnam",
      "kyrgyzstan",
      "57",
    ],
  },
  {
    id: "tool-currency",
    title: "China Currency Converter",
    href: "/china-currency-converter",
    description:
      "Convert USD, EUR, GBP, and more to Chinese Yuan (RMB) with live mid-market rates.",
    type: "tool",
    keywords: [
      "currency",
      "exchange",
      "CNY",
      "RMB",
      "yuan",
      "USD",
      "converter",
      "汇率",
    ],
  },
  {
    id: "tool-planner",
    title: "China Itinerary Planner",
    href: "/china-itinerary-planner",
    description: "Plan cities, days, and routes for your China trip.",
    type: "tool",
    keywords: ["itinerary", "route", "planner", "trip plan"],
  },
  {
    id: "page-services",
    title: "China Itinerary Planning Service & Pricing",
    href: "/services",
    description:
      "Custom itinerary pricing, itinerary review, on-trip Q&A packs, and transparent booking help.",
    type: "tool",
    keywords: [
      "services",
      "pricing",
      "custom itinerary",
      "planning fee",
      "booking help",
    ],
  },
  {
    id: "page-custom-itinerary",
    title: "Custom China Itinerary Planning",
    href: "/services/custom-itinerary",
    description:
      "Local PDF route for independent travelers — what’s included, USD fees, and a labeled sample (not a client trip).",
    type: "tool",
    keywords: [
      "custom itinerary",
      "itinerary PDF",
      "planning service",
      "sample route",
    ],
  },
  {
    id: "page-reviews",
    title: "Traveler notes",
    href: "/reviews",
    description:
      "Permissioned quotes from completed itineraries. The list stays empty until we have written permission.",
    type: "page",
    keywords: ["reviews", "testimonials", "traveler notes"],
  },
  {
    id: "page-partners",
    title: "Planner partnerships",
    href: "/partners",
    description:
      "Work with independent itinerary planners and travel writers — not tour agencies.",
    type: "page",
    keywords: ["partnership", "itinerary planner", "collaboration"],
  },

  // Hubs
  {
    id: "hub-payments",
    title: "Payments in China for Foreigners",
    href: "/payments-in-china",
    description:
      "How to pay in China as a foreigner — Alipay, WeChat Pay, foreign cards, cash backup, and common payment failures.",
    type: "hub",
    keywords: ["alipay", "wechat pay", "money", "card", "payment", "cash"],
  },
  {
    id: "hub-internet",
    title: "Internet in China for Foreigners",
    href: "/internet-in-china",
    description:
      "VPN, SIM, and eSIM choices so Google, WhatsApp, and maps work on your trip.",
    type: "hub",
    keywords: ["sim", "esim", "vpn", "data", "internet", "firewall"],
  },
  {
    id: "hub-maps",
    title: "Maps & Navigation in China for Foreigners",
    href: "/maps-navigation-in-china",
    description:
      "Why Google Maps feels unreliable in China and how to navigate with better prep.",
    type: "hub",
    keywords: ["maps", "navigation", "amap", "baidu", "google maps"],
  },
  {
    id: "hub-transport",
    title: "Transport in China for Foreigners",
    href: "/transport-in-china",
    description:
      "High-speed rail, metro, and DiDi — plus the payment and data setup that unlocks them.",
    type: "hub",
    keywords: ["train", "metro", "12306", "didi", "transport"],
  },
  {
    id: "hub-food",
    title: "Food & Delivery in China for Foreigners",
    href: "/food-delivery-in-china",
    description:
      "QR menus, Meituan, and ordering food without a Chinese phone number.",
    type: "hub",
    keywords: ["meituan", "eleme", "delivery", "qr menu", "food"],
  },
  {
    id: "hub-hotels",
    title: "Hotels in China for Foreigners",
    href: "/hotels-in-china",
    description:
      "Book hotels that accept foreign guests and understand passport check-in.",
    type: "hub",
    keywords: ["hotel", "check-in", "accommodation", "passport"],
  },
  {
    id: "hub-tickets",
    title: "Attraction Tickets in China for Foreigners",
    href: "/attraction-tickets-in-china",
    description:
      "Book sightseeing tickets with a passport and avoid real-name entry issues.",
    type: "hub",
    keywords: ["tickets", "attractions", "sights", "real-name"],
  },
  {
    id: "hub-essentials",
    title: "China Travel Essentials for Foreigners",
    href: "/china-travel-essentials",
    description:
      "Independent travel prep: payments, internet, maps, hotels, tickets, and real-name rules.",
    type: "hub",
    keywords: ["essentials", "prep", "independent travel", "checklist"],
  },
  {
    id: "hub-itinerary",
    title: "China Itinerary Planning for Independent Travelers",
    href: "/china-itinerary-planning",
    description:
      "How to plan an independent China itinerary: city pacing, rail backbone, DIY vs a local PDF.",
    type: "hub",
    keywords: [
      "itinerary",
      "trip planning",
      "independent itinerary",
      "how many days",
    ],
  },

  // Planned / mapped articles
  {
    id: "article-payment-guide",
    title: "How to Pay in China as a Foreigner",
    href: "/digital-survival-china-payment-guide",
    description: "Full guide to mobile payments for foreign visitors.",
    type: "article",
    keywords: ["payment", "alipay", "wechat"],
  },
  {
    id: "article-alipay",
    title: "Alipay for Foreigners in China",
    href: "/alipay-for-foreigners-china",
    description: "Set up and use Alipay with a foreign passport.",
    type: "article",
    keywords: ["alipay"],
  },
  {
    id: "article-wechat-pay",
    title: "WeChat Pay for Foreigners in China",
    href: "/wechat-pay-for-foreigners-china",
    description: "Set up WeChat Pay as a foreign traveler.",
    type: "article",
    keywords: ["wechat pay", "wechat"],
  },
  {
    id: "article-payment-fails",
    title: "Why Your Payment Fails in China",
    href: "/why-your-payment-fails-in-china",
    description: "Common payment failures and how to fix them.",
    type: "article",
    keywords: ["payment failed", "decline"],
  },
  {
    id: "article-verification",
    title: "Alipay & WeChat Pay Verification Failed",
    href: "/alipay-wechat-pay-verification-failed",
    description: "What to do when payment verification fails.",
    type: "article",
    keywords: ["verification", "real-name"],
  },
  {
    id: "article-internet",
    title: "Internet & VPN in China",
    href: "/digital-survival-china-internet-guide",
    description: "Stay online: SIM, eSIM, and VPN basics.",
    type: "article",
    keywords: ["internet", "vpn"],
  },
  {
    id: "article-sim",
    title: "China SIM Card for Foreigners",
    href: "/china-sim-card-for-foreigners",
    description: "Buying and activating a local SIM as a visitor.",
    type: "article",
    keywords: ["sim card"],
  },
  {
    id: "article-esim",
    title: "Best eSIM for China Travel",
    href: "/best-esim-for-china-travel",
    description: "eSIM options that work for foreign travelers.",
    type: "article",
    keywords: ["esim", "airalo"],
  },
  {
    id: "article-vpn",
    title: "Do You Need a VPN in China?",
    href: "/do-you-need-vpn-china",
    description: "When a VPN helps and how to prepare before you land.",
    type: "article",
    keywords: ["vpn", "nordvpn", "expressvpn"],
  },
  {
    id: "article-maps",
    title: "Why Google Maps Doesn’t Work Properly in China",
    href: "/google-maps-china-not-working",
    description: "Navigation alternatives that actually work.",
    type: "article",
    keywords: ["google maps", "maps"],
  },
  {
    id: "article-transport",
    title: "Transport in China Guide",
    href: "/digital-survival-china-transport-guide",
    description: "Trains, metro, and apps for getting around.",
    type: "article",
    keywords: ["transport", "train"],
  },
  {
    id: "article-hsr-booking",
    title: "Book High-Speed Rail Tickets in China",
    href: "/book-china-high-speed-rail-foreigners",
    description:
      "12306 vs Trip.com, Chongqing to Dali walkthrough, and sold-out backups.",
    type: "article",
    keywords: [
      "high-speed rail",
      "train tickets",
      "12306",
      "trip.com",
      "chongqing",
      "dali",
    ],
  },
  {
    id: "article-didi",
    title: "How to Use DiDi in China as a Foreigner",
    href: "/how-to-use-didi-china-foreigners",
    description:
      "DiDi app, Alipay/WeChat mini-program, or Amap taxi — plate checks, Safety Center, payment.",
    type: "article",
    keywords: ["didi", "taxi", "ride-hailing", "uber china", "pickup"],
  },
  {
    id: "article-food",
    title: "How to Order Food Without a Chinese Number",
    href: "/order-food-china-without-chinese-number",
    description: "Food delivery when you lack a local phone number.",
    type: "article",
    keywords: ["food", "delivery"],
  },
  {
    id: "article-hotels",
    title: "Hotels in China for Foreigners",
    href: "/hotels-in-china-for-foreigners",
    description: "Booking and checking in with a foreign passport.",
    type: "article",
    keywords: ["hotels"],
  },
  {
    id: "article-tickets",
    title: "How Foreigners Can Book Attraction Tickets",
    href: "/china-attraction-ticket-booking-foreigners-2026",
    description: "Passport-based ticket booking for sights.",
    type: "article",
    keywords: ["tickets", "attractions"],
  },
  {
    id: "article-tickets-why-reserve",
    title: "Why China Attractions Require Reservations",
    href: "/why-china-attractions-require-reservations",
    description: "Timed entry, crowd control, and what first-timers should check before going.",
    type: "article",
    keywords: ["reservation", "timed entry", "attractions", "tickets"],
  },
  {
    id: "article-real-name",
    title: "China’s Real-Name System for Foreigners",
    href: "/china-real-name-system-foreigners",
    description: "How real-name rules affect apps and travel.",
    type: "article",
    keywords: ["real-name", "passport"],
  },
  {
    id: "article-independent",
    title: "Independent Travel in China",
    href: "/independent-travel-china",
    description: "Is China safe and practical for independent travel?",
    type: "article",
    keywords: ["independent", "safety"],
  },
  {
    id: "article-plan-itinerary",
    title: "How to Plan a China Itinerary Independently",
    href: "/how-to-plan-china-itinerary",
    description:
      "City count, high-speed rail as the backbone, rest days, and when a local planner is worth the fee.",
    type: "article",
    keywords: ["plan itinerary", "itinerary", "diy china trip"],
  },
  {
    id: "article-visa-need",
    title: "Do I Need a Visa for China?",
    href: "/do-i-need-a-visa-for-china",
    description: "Quick check on visa requirements for your trip.",
    type: "article",
    keywords: ["visa", "entry"],
  },
  {
    id: "article-visa-free-list",
    title: "China Visa-Free Countries List 2026",
    href: "/china-visa-free-countries-2026",
    description: "Countries eligible for short visa-free stays and 240-hour transit.",
    type: "article",
    keywords: [
      "visa-free",
      "countries",
      "2026",
      "transit",
      "240",
      "vietnam",
      "kyrgyzstan",
    ],
  },
];
